const { createDomExtractor } = require('./base');

module.exports = createDomExtractor({
  providerKey: 'gemini',
  displayName: 'Gemini',
  hostPatterns: ['gemini.google.com'],
  rootSelectors: [
    'main model-response',
    'main [data-response-id]',
    'model-response[data-response-id]',
    'main .response-container',
  ],
  contentSelectors: [
    'model-response message-content',
    '[data-response-id] message-content',
    'message-content',
    '.markdown',
    '[class*="markdown"]',
    '.model-response-text',
    '.response-content',
  ],
  excludeSelectors: [
    'rich-textarea',
    'div[role="textbox"][contenteditable="true"]',
    '[contenteditable="true"]',
    'textarea',
    'form',
  ],
  errorSelectors: [
    '[role="alert"]',
    '[aria-live="assertive"]',
    'mat-snack-bar-container',
    '.mat-mdc-snack-bar-container',
    '[class*="snack"]',
    '[class*="toast"]',
  ],
  errorTextPatterns: [
    'something went wrong',
    'went wrong',
    'try again',
    '发生问题',
    '出了问题',
    '出了点问题',
    '请重试',
    '重试',
    '(13)',
  ],
  busySelectors: [
    'button[aria-label*="Stop"]',
    'button[aria-label*="Cancel"]',
    'button[mattooltip*="Stop"]',
    '[data-test-id*="stop"]',
  ],
  busyTextPatterns: [
    'stop generating',
    'stop response',
    'cancel',
  ],
  noisePatterns: [
    'copy',
    'edit',
    'google it',
  ],
  weakTextPatterns: [
    'gemini 話',
    'gemini话',
  ],
  minRootTextLength: 30,
  shortTextThreshold: 24,
  weakTextMaxLength: 24,
  minimumUsableConfidence: 0.34,
  minimumShortTextConfidence: 0.58,
  busyWait: {
    pollIntervalMs: 700,
    timeoutMs: 45000,
  },
  stability: {
    pollIntervalMs: 700,
    stablePassesRequired: 5,
    minIdleStableMs: 3200,
    timeoutMs: 24000,
  },
});
